title: My GitHub.io Site
description: A personal website with top navigation
baseurl: "" 
url: "https://bipulmani.github.io"

theme: null

# Site-wide navigation
nav_items:
  - name: Home
    url: /
  - name: About
    url: /about/
  - name: Projects
    url: /projects/
