title: My GitHub.io Site
description: A personal website with top navigation
baseurl: "" # for user.github.io
url: "https://yourusername.github.io"

theme: null # we're using a custom layout, so disable default theme

# Site-wide navigation
nav_items:
  - name: Home
    url: /
  - name: About
    url: /about/
  - name: Projects
    url: /projects/
